language: node_js

node_js:
  - 18.12.0

services:
  - docker

before_script:
  - docker pull manuelvico0102/easyselect:latest

script:
  - docker build -t manuelvico0102/easyselect .
  - docker run  -tv `pwd`:/app/test manuelvico0102/easyselect